import pygame as pg

HEIGHT = 720
WIDTH = 1280
FPS = 60
TITLE = 'INVADERS'
SHIP_SPEED = 5
LASER_SPEED = 10
PILL_SPEED = 3
METEOR_SPEED = 3
MUSIC_VOLUME = 0.5
LASER_SCALE = 0.5
SHIP_SCALE = 1
PILL_SCALE = 1
METEOR_SCALE = 0.35
HEART_SCALE = 2
BACKGROUND_SCALE = 5
ADD_METEOR = pg.USEREVENT + 1
ADD_PILL = pg.USEREVENT + 2
POWERUP_COOLDOWN = 5000
